{% set version = "8.0" %}

package:
  name: xppaut
  version: "{{ version }}"

source:
  url: https://sites.pitt.edu/~phase/bard/bardware/xpp/xppaut{{ version }}.tgz
  sha256: d0a2d2c7a6bef9bbee879190e081d01c52ec46784085c05a43f99cca22ecc7a8

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - make                 # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib('c') }}    # [unix]
  host:
    - xorg-libx11
    - libgl-devel          # [linux]
  run:
    - xorg-libx11

test:
  commands:
    - xppaut --version

about:
  home: http://www.math.pitt.edu/~bard/xpp/xpp.html
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'A tool for solving differential equations.'

extra:
  recipe-maintainers:
    - hmaarrfk
